// app/layout.js (or app/layout.tsx if you're using TypeScript)
import { Geist, Geist_Mono } from 'next/font/google';
import '../styles/globals.css'; // Make sure the path is correct

// Load fonts
const geistSans = Geist({
  subsets: ['latin'],
  variable: '--font-geist-sans',
  display: 'swap', // Recommended for better performance
});

const geistMono = Geist_Mono({
  subsets: ['latin'],
  variable: '--font-geist-mono',
  display: 'swap',
});

// Metadata for SEO (Optional: can be moved to a separate file for cleaner structure)
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="antialiased">
        {children}
      </body>
    </html>
  );
}
